name: CI/CD Pipeline

on:
  push:
    branches: 
      - master
    paths: # this will trigger actions only when changes are detected inside listed paths
      - 'packages/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and Push First Server
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./packages/first-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/first-server:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

